
import UserHomePage from '@/Components/UserHomePage/UserHomePage';
import React from 'react';

export const metadata = {
  title: "InstaCity",
  description: "Generated by Tamzid",
};



const Home = () => {


  return (
    <div className="px-4 h-[86vh] bg-white text-black pt-5">
      <UserHomePage />
    </div>
  );
}

export default Home;





