
export const metadata = {
  title: "InstaCity",
  description: "Generated by Tamzid",
};

const  Home = ()  =>  {
  return (
   <div className="px-4">
<h1>Home</h1>
   </div>
  );
}

export default  Home ;
