
export const metadata = {
  title: "InstaCity",
  description: "Generated by Tamzid",
};

const  Home = ()  =>  {
  return (
   <div className="bg-gray-800 max-w-lg h-screen mx-auto">

   </div>
  );
}

export default  Home ;
